name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable and Build APK
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" -print -quit)
          GRADLE_DIR=$(dirname "$GRADLEW_PATH")
          cd "$GRADLE_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TheFightOfNature-APK
          path: '**/app/build/outputs/apk/debug/app-debug.apk'

